apiVersion: v1
kind: Service 
metadata: 
  name: simple-app-service
spec:
  selector:
    app: simple-app
  ports: 
    - protocol: TCP
      port: 8080
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
spec:
  selector:
    matchLabels:
      app: simple-app
  replicas: 2
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app
        image: simple-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
